services:
  rstudio:
    build: dev/docker
    ports:
      - "8787:8787"
    environment:
      - TZ=${LOCAL_TZ}
      - PASSWORD=password
      - DISABLE_AUTH=true
    volumes:
      - .:${PROJECT_PATH_CONTAINER:-/home/rstudio/project}
      - ${DOTFILES_ROOT:-./dev/dotfiles}:/home/rstudio/dotfiles
      - ${GITHUB_SSH_IDENTITY:-/dev/null}:/home/rstudio/.ssh/id_github:ro
